name: Waka Readme Stats

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: languages, projects, editors
          plugin_wakatime_user: current
